Salon owner - revised mobile, implemented desktop
PiotrDrechsler/spoondog pull request #30
Opened 2024-09-16 16:38 UTC by Delicadency

Most of the styles have been revised or rewritten to best reflect the design. I replaced the image file to allow lossless rendering of the image for desktops, added additional parameters for the Image component. I corrected the size of the Container component and replaced the button tag with a reusable component created earlier.

2024-09-17 13:24 UTC, AgnieszkaIwan approved these changes

2024-09-21 11:31 UTC, PiotrDrechsler requested changes
@Delicadency your code looks very good and is already solidly organized. Good Job! :) I have only added a few minor comments. Please make corrections and we will merge your code into the dev! :)

2024-09-21 11:31 UTC, PiotrDrechsler commented on src/app/components/SalonOwner/SalonOwner.tsx
> +            <p className="mb-4 text-left text-16 text-sm leading-6 tracking-[-.32px] desktop:mb-4 desktop:text-18 desktop:font-medium desktop:tracking-normal">
Delete the redundant class, text-sm, when text-16 is already in use, which automatically sets the correct size :)

2024-09-21 11:31 UTC, PiotrDrechsler commented on src/app/components/SalonOwner/SalonOwner.tsx
> +              alt="Katarzyna Bober"
You can improve the description in the alt to better reflect the content of the image, which is good for both SEO and users using screen readers. eg: alt="Katarzyna Bober, właścicielka salonu groomerskiego Spoon Dog"

2024-09-21 15:36 UTC, merged