Hero
PiotrDrechsler/spoondog pull request #39
Opened 2024-10-04 13:01 UTC by Anmakulaku

I added changes to hero.

2024-10-10 10:35 UTC, Delicadency requested changes
The code is already looking better and better, but there are still places that can be slightly improved :) I've pointed out some minor improvements in the comments. Also pay attention to the formatting of the code, as there are blank lines or unsorted styles in each component from Hero. Do you have Prettier configured correctly?

I am also concerned about the appearance of Hero on wide screen. I've uploaded a screen shot below. Should the image actually always be on the far right of the screen, regardless of the container?

![image](https://github.com/user-attachments/assets/f4826089-6200-4b6e-8fa2-a50258db112f)

Also note the spacing between the description section and the icons at the bottom of the component - it seems to me that the spacing relative to the design is not maintained.

2024-10-10 10:35 UTC, Delicadency commented on src/app/components/Hero/HeroInfo.tsx
>      <>
React fragment is unnecessary here, since the topmost element is a div that already surrounds the whole thing.

2024-10-10 10:35 UTC, Delicadency commented on src/app/components/Hero/HeroInfo.tsx
>            </a>
Shouldn't the Link component be used here instead of a?

2024-10-14 15:16 UTC, NacomiTagiera approved these changes

2024-10-15 18:10 UTC, PiotrDrechsler approved these changes
Corrections carried out in accordance with all comments :) You may merge. Well done @Anmakulaku!

2024-10-15 19:08 UTC, NacomiTagiera approved these changes

2024-10-16 04:49 UTC, Delicadency approved these changes
All nicely done :) you can merge

2024-10-18 10:05 UTC, merged