Home/sekcja opinie
PiotrDrechsler/spoondog pull request #40
Opened 2024-10-04 16:18 UTC by PiotrDrechsler

## `OpinionsSection` Component

The `OpinionsSection` component is responsible for rendering a section on the page dedicated to customer opinions. This component organizes and displays customer reviews in a visually appealing manner, enhancing user engagement and trust.

### Props

This component does not accept any props.

### Features

- **Semantic Section**: The component is wrapped in a `<section>` tag with the ID `"opinions"`, which allows for easy navigation and improved SEO.

- **Container**: The entire section is enclosed within a `Container` component to maintain consistent padding and layout across different screen sizes.

- **Section Heading**: The `SectionHeading` component is used to display the title, main heading, and additional information for the opinions section, which helps improve the semantic structure of the content.

- **Google Review Card**: A `GoogleReviewCard` is positioned absolutely within the section, providing visibility to important reviews and enhancing trustworthiness.

- **Swiper for Reviews**: The component utilizes a `Swiper` to create a horizontal scrolling effect for the opinions. This is particularly useful for showcasing multiple reviews in a compact format.

### Child Components

- **`Container`**: This wraps the content of the section to provide proper alignment and spacing.

- **`SectionHeading`**: Displays the section title, main heading, and additional information.

- **`GoogleReviewCard`**: An informational card that presents a Google review, enhancing the credibility of the section.

- **`Swiper`**: A carousel component that enables horizontal scrolling for the `OpinionsCardItem` components.

- **`OpinionsCardItem`**: Represents individual opinion items, each displaying a customer's name and their opinion.

### Example Usage

```jsx
<OpinionsSection />
```

## `OpinionsCardItem` Component

The `OpinionsCardItem` component is responsible for displaying individual customer opinions. It provides a structured layout for the customer's name, their opinion, and a star rating icon, while also ensuring that the opinion text adheres to specified length constraints.

### Props

- **`name: string`**  
  The name of the customer providing the opinion. This will be displayed prominently at the top of the card.

- **`opinion: string`**  
  The customer's opinion or review text. This should not exceed 120 characters for optimal display.

### Features

- **Input Validation**: The component utilizes Zod to validate the opinion length. If the opinion exceeds 120 characters, it will be truncated, and a warning will be logged in the console.

- **Star Rating Icon**: The `IconStars` component is used to visually represent the customer’s rating, adding a graphical element to the opinion card.

### Example Usage

```jsx
<OpinionsCardItem name="John Doe" opinion="This service was excellent! Highly recommend!" />
```

## `GoogleReviewCard` Component

The `GoogleReviewCard` component displays a card featuring Google branding and is designed to showcase customer reviews. It provides a visual element that enhances the credibility of the opinions section.

### Features

- **Card Layout**: The card is styled with a shadow effect, rounded corners, and a white background, making it visually distinct.
- **Typography**: The card includes a bold title "Google" and the text "Opinie," enhancing clarity and readability.
- **Icon Integration**: The `IconGoogle` component is included to visually represent the Google brand, adding to the overall aesthetic.

### Example Usage

```jsx
<GoogleReviewCard />

2024-10-05 14:07 UTC, Delicadency approved these changes
A piece of solid work. The whole thing is well written, very consistent with the rest of the project. The components are well described, so there is no problem in their possible modification or use elsewhere. 

I have no reservations, go ahead and merge :)

2024-10-05 21:23 UTC, NacomiTagiera requested changes
The **Opinions** component you've written is clear and aesthetically pleasing, and the **Swiper** component has been nicely refactored with clean and concise code. I have just a few minor, mostly cosmetic comments for you. Overall, well done! :)

2024-10-07 08:23 UTC, PiotrDrechsler commented on src/app/components/Share/Swiper/Swiper.tsx
> +  noPaddingBottom?: boolean;
Valuable comment, I think you are right. I will change the name to removePaddingBottom :)

2024-10-07 08:36 UTC, PiotrDrechsler commented on src/app/icons/IconGoogle.tsx
> +}
Yes it will be a good change. I will add a shuffle on trello to make these changes in a separate PR.

2024-10-07 08:50 UTC, PiotrDrechsler commented on src/app/components/Share/SectionHeading.tsx
> +      >
Another good point @NacomiTagiera . I was not aware of this patent and would love to start using it in code. I added in 3 places cn() as you suggested. Thanks for the new knowledge :)

2024-10-07 09:46 UTC, NacomiTagiera approved these changes

2024-10-07 10:14 UTC, merged